@test_HostAddress = https://localhost:7106

GET {{test_HostAddress}}/api/products

###

POST {{test_HostAddress}}/api/products
Content-Type: application/json

{
  "name": "Prodotto",
  "price": "10"
}

###



GET {{test_HostAddress}}/api/todos

###

POST {{test_HostAddress}}/api/todos
Content-Type: application/json

{
  "title": "fare la spesa"
}

###

@id=0
DELETE {{test_HostAddress}}/api/todos/1

###

PUT {{test_HostAddress}}/api/todos/1
Content-Type: application/json

{
  "Title": "fatta la spesa!",
  "isCompleted": true
}

###
